final List<Map<String, dynamic>> borrowedBooksData = [
  {
    'borrowID': 'B001',
    'reservationID': 'R001',
    'userID': 'U001',
    'name': 'John Doe',
    'bookName': 'Flutter for Beginners',
    'borrowDate': '2025-04-14',
    'dueDate': '2025-04-28',
    'returnDate': null,
    'status': 'Returned',
    'bookConditionBefore': 'Good',
    'bookConditionAfter': null,
    'penaltyAmount': null,
  },
  {
    'borrowID': 'B002',
    'reservationID': 'R002',
    'userID': 'U002',
    'name': 'Jane Smith',
    'bookName': 'Advanced Dart Programming',
    'borrowDate': '2025-04-15',
    'dueDate': '2025-04-29',
    'returnDate': null,
    'status': 'Overdue',
    'bookConditionBefore': 'Good',
    'bookConditionAfter': null,
    'penaltyAmount': null,
  },
  {
    'borrowID': 'B003',
    'reservationID': 'R003',
    'userID': 'U003',
    'name': 'Alice Brown',
    'bookName': 'Mastering Flutter',
    'borrowDate': '2025-04-16',
    'dueDate': '2025-04-30',
    'returnDate': null,
    'status': 'Returned',
    'bookConditionBefore': 'Fair',
    'bookConditionAfter': null,
    'penaltyAmount': null,
  },
  {
    'borrowID': 'B004',
    'reservationID': 'R004',
    'userID': 'U004',
    'name': 'Bob White',
    'bookName': 'Clean Code: A Handbook of Agile Software Craftsmanship',
    'borrowDate': '2025-04-17',
    'dueDate': '2025-05-01',
    'returnDate': null,
    'status': 'Returned',
    'bookConditionBefore': 'Excellent',
    'bookConditionAfter': null,
    'penaltyAmount': null,
  },
  {
    'borrowID': 'B005',
    'reservationID': 'R005',
    'userID': 'U005',
    'name': 'Charlie Green',
    'bookName': 'Learning Python',
    'borrowDate': '2025-04-18',
    'dueDate': '2025-05-02',
    'returnDate': null,
    'status': 'Pending',
    'bookConditionBefore': 'Good',
    'bookConditionAfter': null,
    'penaltyAmount': null,
  },
  {
    'borrowID': 'B006',
    'reservationID': 'R006',
    'userID': 'U006',
    'name': 'Eve Black',
    'bookName': 'The Pragmatic Programmer',
    'borrowDate': '2025-04-19',
    'dueDate': '2025-05-03',
    'returnDate': null,
    'status': 'Approved',
    'bookConditionBefore': 'Good',
    'bookConditionAfter': null,
    'penaltyAmount': null,
  },
  {
    'borrowID': 'B007',
    'reservationID': 'R007',
    'userID': 'U007',
    'name': 'David Blue',
    'bookName':
        'Design Patterns: Elements of Reusable Object-Oriented Software',
    'borrowDate': '2025-04-20',
    'dueDate': '2025-05-04',
    'returnDate': null,
    'status': 'Damaged',
    'bookConditionBefore': 'Fair',
    'bookConditionAfter': null,
    'penaltyAmount': null,
  },
  {
    'borrowID': 'B008',
    'reservationID': 'R008',
    'userID': 'U008',
    'name': 'Grace Yellow',
    'bookName': 'JavaScript: The Good Parts',
    'borrowDate': '2025-04-21',
    'dueDate': '2025-05-05',
    'returnDate': null,
    'status': 'Pending',
    'bookConditionBefore': 'Good',
    'bookConditionAfter': null,
    'penaltyAmount': null,
  },
  {
    'borrowID': 'B009',
    'reservationID': 'R009',
    'userID': 'U009',
    'name': 'Henry Violet',
    'bookName': 'Eloquent JavaScript',
    'borrowDate': '2025-04-22',
    'dueDate': '2025-05-06',
    'returnDate': null,
    'status': 'Approved',
    'bookConditionBefore': 'Good',
    'bookConditionAfter': null,
    'penaltyAmount': null,
  },
  {
    'borrowID': 'B010',
    'reservationID': 'R010',
    'userID': 'U010',
    'name': 'Isla Gray',
    'bookName': 'Python Crash Course',
    'borrowDate': '2025-04-23',
    'dueDate': '2025-05-07',
    'returnDate': null,
    'status': 'Pending',
    'bookConditionBefore': 'Excellent',
    'bookConditionAfter': null,
    'penaltyAmount': null,
  },
  {
    'borrowID': 'B011',
    'reservationID': 'R011',
    'userID': 'U011',
    'name': 'Jack Silver',
    'bookName': 'Effective Java',
    'borrowDate': '2025-04-24',
    'dueDate': '2025-05-08',
    'returnDate': null,
    'status': 'Overdue',
    'bookConditionBefore': 'Fair',
    'bookConditionAfter': null,
    'penaltyAmount': null,
  },
  {
    'borrowID': 'B012',
    'reservationID': 'R012',
    'userID': 'U012',
    'name': 'Kelly Red',
    'bookName': 'Code Complete',
    'borrowDate': '2025-04-25',
    'dueDate': '2025-05-09',
    'returnDate': null,
    'status': 'Approved',
    'bookConditionBefore': 'Good',
    'bookConditionAfter': null,
    'penaltyAmount': null,
  },
  {
    'borrowID': 'B013',
    'reservationID': 'R013',
    'userID': 'U013',
    'name': 'Leo Orange',
    'bookName': 'Head First Design Patterns',
    'borrowDate': '2025-04-26',
    'dueDate': '2025-05-10',
    'returnDate': null,
    'status': 'Returned',
    'bookConditionBefore': 'Excellent',
    'bookConditionAfter': null,
    'penaltyAmount': null,
  },
  {
    'borrowID': 'B014',
    'reservationID': 'R014',
    'userID': 'U014',
    'name': 'Mia Indigo',
    'bookName': 'You Don’t Know JS',
    'borrowDate': '2025-04-27',
    'dueDate': '2025-05-11',
    'returnDate': null,
    'status': 'Damaged',
    'bookConditionBefore': 'Good',
    'bookConditionAfter': null,
    'penaltyAmount': null,
  },
  {
    'borrowID': 'B015',
    'reservationID': 'R015',
    'userID': 'U015',
    'name': 'Noah Teal',
    'bookName': 'Refactoring',
    'borrowDate': '2025-04-28',
    'dueDate': '2025-05-12',
    'returnDate': null,
    'status': 'Overdue',
    'bookConditionBefore': 'Fair',
    'bookConditionAfter': null,
    'penaltyAmount': null,
  },
  {
    'borrowID': 'B016',
    'reservationID': 'R016',
    'userID': 'U016',
    'name': 'Olivia Gold',
    'bookName': 'The Mythical Man-Month',
    'borrowDate': '2025-04-29',
    'dueDate': '2025-05-13',
    'returnDate': null,
    'status': 'Approved',
    'bookConditionBefore': 'Good',
    'bookConditionAfter': null,
    'penaltyAmount': null,
  },
  {
    'borrowID': 'B017',
    'reservationID': 'R017',
    'userID': 'U017',
    'name': 'Paul Rose',
    'bookName': 'Structure and Interpretation of Computer Programs',
    'borrowDate': '2025-04-30',
    'dueDate': '2025-05-14',
    'returnDate': null,
    'status': 'Pending',
    'bookConditionBefore': 'Fair',
    'bookConditionAfter': null,
    'penaltyAmount': null,
  },
  {
    'borrowID': 'B018',
    'reservationID': 'R018',
    'userID': 'U018',
    'name': 'Quinn Cyan',
    'bookName': 'Cracking the Coding Interview',
    'borrowDate': '2025-05-01',
    'dueDate': '2025-05-15',
    'returnDate': null,
    'status': 'Overdue',
    'bookConditionBefore': 'Good',
    'bookConditionAfter': null,
    'penaltyAmount': null,
  },
  {
    'borrowID': 'B019',
    'reservationID': 'R019',
    'userID': 'U019',
    'name': 'Rachel Aqua',
    'bookName': 'Grokking Algorithms',
    'borrowDate': '2025-05-02',
    'dueDate': '2025-05-16',
    'returnDate': null,
    'status': 'Damaged',
    'bookConditionBefore': 'Excellent',
    'bookConditionAfter': null,
    'penaltyAmount': null,
  },
  {
    'borrowID': 'B020',
    'reservationID': 'R020',
    'userID': 'U020',
    'name': 'Sam Mint',
    'bookName': 'Don’t Make Me Think',
    'borrowDate': '2025-05-03',
    'dueDate': '2025-05-17',
    'returnDate': null,
    'status': 'Approved',
    'bookConditionBefore': 'Good',
    'bookConditionAfter': null,
    'penaltyAmount': null,
  },
];
